package br.com.system.services;

import br.com.system.data.dto.request.StockMovementItemRequestDTO;
import br.com.system.data.dto.request.StockMovementRequestDTO;
import br.com.system.data.dto.response.StockMovementItemResponseDTO;
import br.com.system.data.dto.response.StockMovementResponseDTO;
import br.com.system.enums.MovementType;
import br.com.system.exception.BusinessException;
import br.com.system.exception.ResourceNotFoundException;
import br.com.system.model.*;
import br.com.system.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

@Service
public class StockMovementServices {
    private final Logger logger = Logger.getLogger(StockMovementServices.class.getName());

    @Autowired
    private StockMovementRepository stockMovementRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private AdministratorRepository administratorRepository;

    @Autowired
    private SupplierRepository supplierRepository;

    @Autowired
    private InventoryService inventoryService;

    @Transactional(readOnly = true)
    public Page<StockMovementResponseDTO> findAll(Pageable pageable) {
        logger.info("Finding stock movements!");

        return stockMovementRepository.findAll(pageable)
                .map(this::toResponseDTO);
    }

    @Transactional(readOnly = true)
    public Page<StockMovementResponseDTO> findByAdmin(Long adminId, Pageable pageable) {
        logger.info("Finding stock movements by administrator!");

        findAdministrator(adminId);

        return stockMovementRepository.findByAdminId(adminId, pageable)
                .map(this::toResponseDTO);
    }

    @Transactional(readOnly = true)
    public Page<StockMovementResponseDTO> findBySupplier(Long supplierId, Pageable pageable) {
        logger.info("Finding stock movements by supplier!");

        findSupplier(supplierId);

        return stockMovementRepository.findBySupplierId(supplierId, pageable)
                .map(this::toResponseDTO);
    }

    @Transactional(readOnly = true)
    public Page<StockMovementResponseDTO> findByType(MovementType type, Pageable pageable) {
        logger.info("Finding stock movements by type!");

        return stockMovementRepository.findByType(type, pageable)
                .map(this::toResponseDTO);
    }

    @Transactional(readOnly = true)
    public StockMovementResponseDTO findById(Long id) {
        logger.info("Finding one stock movement!");

        return toResponseDTO(findMovement(id));
    }

    @Transactional
    public StockMovementResponseDTO create(StockMovementRequestDTO dto) {
        logger.info("Creating one stock movement!");

        validateMovementRules(dto);

        Administrator admin = findAdminFromToken();
        Supplier supplier = dto.getSupplierId() == null ? null : findSupplier(dto.getSupplierId());

        StockMovement entity = new StockMovement();
        entity.setType(dto.getType());
        entity.setReason(dto.getReason());
        entity.setObservation(dto.getObservation());
        entity.setExitReason(dto.getExitReason());
        entity.setAdmin(admin);
        entity.setSupplier(supplier);

        List<StockMovementItem> items = buildItems(dto.getItems(), entity, false);
        entity.setItems(items);

        return toResponseDTO(stockMovementRepository.save(entity));
    }

    @Transactional
    public void delete(Long id) {
        logger.info("Deleting one stock movement!");

        StockMovement entity = findMovement(id);

        if (entity.getType() == MovementType.SALE) {
            throw new BusinessException("Cannot delete a movement generated by a sale!");
        }

        reverseMovement(entity);
        stockMovementRepository.delete(entity);
    }

    @Transactional
    public void createFromSale(Sale sale) {
        logger.info("Creating stock movement from sale!");

        StockMovement entity = buildSaleMovement(sale);
        for (StockMovementItem item : entity.getItems()) {
            inventoryService.decrease(item.getProduct(), item.getQuantity());
        }

        stockMovementRepository.save(entity);
    }

    @Transactional
    public void applyOrCreateFromSale(Sale sale) {
        stockMovementRepository.findBySaleId(sale.getId())
                .ifPresentOrElse(movement -> {
                    movement.getItems().clear();
                    movement.getItems().addAll(buildSaleItems(sale, movement));
                    for (StockMovementItem item : movement.getItems()) {
                        inventoryService.decrease(item.getProduct(), item.getQuantity());
                    }
                    stockMovementRepository.save(movement);
                }, () -> createFromSale(sale));
    }

    @Transactional
    public void synchronizeFromSale(Sale sale) {
        stockMovementRepository.findBySaleId(sale.getId())
                .ifPresentOrElse(movement -> {
                    movement.getItems().clear();
                    movement.getItems().addAll(buildSaleItems(sale, movement));
                    stockMovementRepository.save(movement);
                }, () -> stockMovementRepository.save(buildSaleMovement(sale)));
    }

    private StockMovement buildSaleMovement(Sale sale) {
        StockMovement entity = new StockMovement();
        entity.setType(MovementType.SALE);
        entity.setSale(sale);
        entity.setAdmin(sale.getAdmin());
        entity.setItems(buildSaleItems(sale, entity));

        return entity;
    }

    private List<StockMovementItem> buildSaleItems(Sale sale, StockMovement movement) {
        List<StockMovementItem> items = new ArrayList<>();
        for (SaleItem saleItem : sale.getItems()) {
            StockMovementItem item = new StockMovementItem();
            item.setStockMovement(movement);
            item.setProduct(saleItem.getProduct());
            item.setQuantity(saleItem.getQuantity());
            items.add(item);
        }

        return items;
    }

    @Transactional
    public boolean reverseFromSale(Sale sale) {
        return stockMovementRepository.findBySaleId(sale.getId())
                .map(movement -> {
                    reverseMovement(movement);
                    return true;
                })
                .orElse(false);
    }

    @Transactional
    public void removeFromSale(Sale sale) {
        stockMovementRepository.findBySaleId(sale.getId())
                .ifPresent(stockMovementRepository::delete);
    }

    // ─── Métodos internos ─────────────────────────────────────────────────────

    private void validateMovementRules(StockMovementRequestDTO dto) {
        if (dto.getItems() == null || dto.getItems().isEmpty()) {
            throw new BusinessException("At least one item is required!");
        }

        if (dto.getType() == MovementType.ADJUSTMENT &&
                (dto.getReason() == null || dto.getReason().isBlank())) {
            throw new BusinessException("Reason is required for adjustments!");
        }

        if (dto.getType() == MovementType.EXIT && dto.getExitReason() == null) {
            throw new BusinessException("Exit reason is required for exits!");
        }

        if (dto.getType() == MovementType.SALE) {
            throw new BusinessException("Sale movements are generated automatically!");
        }
    }

    private List<StockMovementItem> buildItems(
            List<StockMovementItemRequestDTO> itemDTOs,
            StockMovement movement,
            boolean reverse) {

        List<StockMovementItem> items = new ArrayList<>();

        for (StockMovementItemRequestDTO itemDTO : itemDTOs) {
            Product product = findProduct(itemDTO.getProductId());
            int quantity = itemDTO.getQuantity();

            StockMovementItem item = new StockMovementItem();
            item.setStockMovement(movement);
            item.setProduct(product);
            item.setQuantity(quantity);

            switch (movement.getType()) {
                case ENTRY -> inventoryService.increase(product, quantity);
                case EXIT -> inventoryService.decrease(product, quantity);
                case ADJUSTMENT -> applyAdjustment(item, product, quantity);
            }

            items.add(item);
        }

        return items;
    }

    private void applyAdjustment(StockMovementItem item, Product product, int quantityReal) {
        int quantityBefore = product.getQuantity();
        int difference = quantityReal - quantityBefore;

        item.setQuantityBefore(quantityBefore);
        item.setQuantityDifference(difference);

        inventoryService.setQuantity(product, quantityReal);
    }

    private void reverseMovement(StockMovement movement) {
        for (StockMovementItem item : movement.getItems()) {
            Product product = item.getProduct();
            switch (movement.getType()) {
                case ENTRY -> inventoryService.decrease(product, item.getQuantity());
                case EXIT, SALE -> inventoryService.increase(product, item.getQuantity());
                case ADJUSTMENT -> {
                    inventoryService.setQuantity(product, item.getQuantityBefore());
                }
            }
        }
    }

    private Administrator findAdminFromToken() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        String login = authentication.getName();

        return administratorRepository.findByLogin(login)
                .orElseThrow(() -> new ResourceNotFoundException("Administrator not found!"));
    }

    private StockMovement findMovement(Long id) {
        return stockMovementRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("No stock movement found for this ID!"));
    }

    private Product findProduct(Long productId) {
        return productRepository.findById(productId)
                .orElseThrow(() -> new ResourceNotFoundException("No product found for this ID!"));
    }

    private Administrator findAdministrator(Long adminId) {
        return administratorRepository.findById(adminId)
                .orElseThrow(() -> new ResourceNotFoundException("No administrator found for this ID!"));
    }

    private Supplier findSupplier(Long supplierId) {
        return supplierRepository.findById(supplierId)
                .orElseThrow(() -> new ResourceNotFoundException("No supplier found for this ID!"));
    }

    // ─── Mapeamento para DTO ──────────────────────────────────────────────────

    private StockMovementResponseDTO toResponseDTO(StockMovement entity) {
        StockMovementResponseDTO dto = new StockMovementResponseDTO();

        dto.setId(entity.getId());
        dto.setType(entity.getType());
        dto.setTypeLabel(entity.getType().getLabel());
        dto.setReason(entity.getReason());
        dto.setObservation(entity.getObservation());
        dto.setDate(entity.getDate());

        if (entity.getExitReason() != null) {
            dto.setExitReason(entity.getExitReason());
            dto.setExitReasonLabel(entity.getExitReason().getLabel());
        }

        if (entity.getAdmin() != null) {
            dto.setAdminId(entity.getAdmin().getId());
            dto.setAdminLogin(entity.getAdmin().getLogin());
        }

        if (entity.getSupplier() != null) {
            dto.setSupplierId(entity.getSupplier().getId());
            dto.setSupplierTradeName(entity.getSupplier().getTradeName());
        }

        if (entity.getSale() != null) {
            dto.setSaleId(entity.getSale().getId());
        }

        dto.setItems(entity.getItems().stream()
                .map(this::toItemResponseDTO)
                .toList());

        return dto;
    }

    private StockMovementItemResponseDTO toItemResponseDTO(StockMovementItem item) {
        StockMovementItemResponseDTO dto = new StockMovementItemResponseDTO();

        dto.setId(item.getId());
        dto.setQuantity(item.getQuantity());
        dto.setQuantityBefore(item.getQuantityBefore());
        dto.setQuantityDifference(item.getQuantityDifference());

        if (item.getProduct() != null) {
            dto.setProductId(item.getProduct().getId());
            dto.setProductName(item.getProduct().getName());
        }

        return dto;
    }
}
